language: node_js
node_js:
    - lts/*
jobs:
    include:
        - stage: test
          script:
              - yarn test
        - stage: deploy
          name: "Deploy to heroku"
          if: branch = develop
          before_deploy:
              - yarn build
          deploy:
              provider: heroku
              app:
                  master: to-do-app
              on: deploy
              api_key:
                  secure: 21a47b23-7126-4836-ba55-1dc6e1b5fb16
