language: node_js
node_js:
- lts/*
jobs:
  include:
  - stage: test
    script:
    - yarn test
  - stage: deploy
    name: Deploy to heroku
    if: branch = develop
    before_deploy:
    - yarn build
    deploy:
      provider: heroku
      app:
        master: to-do-app
      on: develop
      api_key:
        secure: VBFCFyuJZCqphxsfKBwton9saktthrzOl+XQB0IKgF0x+L/iVf6DPKPwbh9bZQomrOxlepbA72ddpf/MXaGeGq6vyxomkmMYjKpI56QIq8hwt0H9wINrNYFEwerW+WjxGUoHjhM8MI/m3DqRlU3lkE7HY4J9A9KeVL3R6Lq+n4vyYj397tsMQzZ+J3nQcx9omz64BFczGwNQ91OUqKQHsmUdkc1cumzYHD8f3P6yCAGgcAvLjrwnik9BBwYLA7tnx8j5HyBoSN+eV3nJjZGxcDxvY1ksM4+nLslJlsct1RKUe87ErVaLs4hs80izVC9HPCLHf4SWAJFGgnJ3rP2l0xKg9RE3QgKzHKUlNq8JZwNC1FA4rN21AwP8/kUAybbyZz/GvLNIt7yiOxLztrlMnu0L+O+InSB+9GsCbgmjCZ2aN3IF5oVvBk5ZLkPhwIZ6qAxCDFzU73sGBA2ZtmMOgP2uaeR4Q45T//3CnhIvt9YJIXc3TbKAPnKSkJfm72mV6AKRCGSNx7SX175VDnKiExWXAEbJc//pNG2Ao83A83VhAFigKF0+PM6+djW0W68hlSWU3NccUz0c9m7xq77ybiemoyZ43hxsTKC/SOqZMQyeuOxpdxN15/Jxwlzf+llca5ZIxPSmNE4AWxM7F68Z+9Bt50fZ7CXZoswAhEEIhZk=
         
