language: node_js
node_js:
    - "12"
jobs:
    include:
        - stage: test
          script:
              - yarn test
        - stage: deploy
          name: "Deploy to heroku"
          if: branch = master
          before_deploy:
              - yarn build